stages:
  - build

variables:
  DOCKER_USERNAME: alexeykarakcheev
  DOCKER_IMAGE: frontend

build_backend:
  stage: build
  script:
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
    - docker build -t $DOCKER_USERNAME/$DOCKER_IMAGE:$CI_COMMIT_SHA .
    - docker tag $DOCKER_USERNAME/$DOCKER_IMAGE:$CI_COMMIT_SHA $DOCKER_USERNAME/$DOCKER_IMAGE:latest
    - docker push $DOCKER_USERNAME/$DOCKER_IMAGE:latest
